export interface Nationality {
  code: string;
  en: string;
  ar: string;
}

// Comprehensive list of nationalities (ISO 3166-1 alpha-2 codes)
export const NATIONALITIES: Nationality[] = [
  { code: "AF", en: "Afghan", ar: "أفغاني" },
  { code: "AL", en: "Albanian", ar: "ألباني" },
  { code: "DZ", en: "Algerian", ar: "جزائري" },
  { code: "AD", en: "Andorran", ar: "أندوري" },
  { code: "AO", en: "Angolan", ar: "أنغولي" },
  { code: "AR", en: "Argentine", ar: "أرجنتيني" },
  { code: "AM", en: "Armenian", ar: "أرميني" },
  { code: "AU", en: "Australian", ar: "أسترالي" },
  { code: "AT", en: "Austrian", ar: "نمساوي" },
  { code: "AZ", en: "Azerbaijani", ar: "أذربيجاني" },
  { code: "BH", en: "Bahraini", ar: "بحريني" },
  { code: "BD", en: "Bangladeshi", ar: "بنغلاديشي" },
  { code: "BY", en: "Belarusian", ar: "بيلاروسي" },
  { code: "BE", en: "Belgian", ar: "بلجيكي" },
  { code: "BO", en: "Bolivian", ar: "بوليفي" },
  { code: "BA", en: "Bosnian", ar: "بوسني" },
  { code: "BR", en: "Brazilian", ar: "برازيلي" },
  { code: "BG", en: "Bulgarian", ar: "بلغاري" },
  { code: "KH", en: "Cambodian", ar: "كمبودي" },
  { code: "CM", en: "Cameroonian", ar: "كاميروني" },
  { code: "CA", en: "Canadian", ar: "كندي" },
  { code: "CL", en: "Chilean", ar: "تشيلي" },
  { code: "CN", en: "Chinese", ar: "صيني" },
  { code: "CO", en: "Colombian", ar: "كولومبي" },
  { code: "KM", en: "Comoran", ar: "قمري" },
  { code: "CR", en: "Costa Rican", ar: "كوستاريكي" },
  { code: "HR", en: "Croatian", ar: "كرواتي" },
  { code: "CU", en: "Cuban", ar: "كوبي" },
  { code: "CY", en: "Cypriot", ar: "قبرصي" },
  { code: "CZ", en: "Czech", ar: "تشيكي" },
  { code: "DK", en: "Danish", ar: "دنماركي" },
  { code: "DJ", en: "Djiboutian", ar: "جيبوتي" },
  { code: "DO", en: "Dominican", ar: "دومينيكي" },
  { code: "EC", en: "Ecuadorian", ar: "إكوادوري" },
  { code: "EG", en: "Egyptian", ar: "مصري" },
  { code: "SV", en: "Salvadoran", ar: "سلفادوري" },
  { code: "EE", en: "Estonian", ar: "إستوني" },
  { code: "ET", en: "Ethiopian", ar: "إثيوبي" },
  { code: "FI", en: "Finnish", ar: "فنلندي" },
  { code: "FR", en: "French", ar: "فرنسي" },
  { code: "GE", en: "Georgian", ar: "جورجي" },
  { code: "DE", en: "German", ar: "ألماني" },
  { code: "GH", en: "Ghanaian", ar: "غاني" },
  { code: "GR", en: "Greek", ar: "يوناني" },
  { code: "GT", en: "Guatemalan", ar: "غواتيمالي" },
  { code: "HT", en: "Haitian", ar: "هايتي" },
  { code: "HN", en: "Honduran", ar: "هندوراسي" },
  { code: "HU", en: "Hungarian", ar: "مجري" },
  { code: "IS", en: "Icelandic", ar: "آيسلندي" },
  { code: "IN", en: "Indian", ar: "هندي" },
  { code: "ID", en: "Indonesian", ar: "إندونيسي" },
  { code: "IR", en: "Iranian", ar: "إيراني" },
  { code: "IQ", en: "Iraqi", ar: "عراقي" },
  { code: "IE", en: "Irish", ar: "أيرلندي" },
  { code: "IL", en: "Israeli", ar: "إسرائيلي" },
  { code: "IT", en: "Italian", ar: "إيطالي" },
  { code: "JM", en: "Jamaican", ar: "جامايكي" },
  { code: "JP", en: "Japanese", ar: "ياباني" },
  { code: "JO", en: "Jordanian", ar: "أردني" },
  { code: "KZ", en: "Kazakhstani", ar: "كازاخستاني" },
  { code: "KE", en: "Kenyan", ar: "كيني" },
  { code: "KW", en: "Kuwaiti", ar: "كويتي" },
  { code: "KG", en: "Kyrgyz", ar: "قيرغيزستاني" },
  { code: "LA", en: "Lao", ar: "لاوسي" },
  { code: "LV", en: "Latvian", ar: "لاتفي" },
  { code: "LB", en: "Lebanese", ar: "لبناني" },
  { code: "LY", en: "Libyan", ar: "ليبي" },
  { code: "LT", en: "Lithuanian", ar: "ليتواني" },
  { code: "LU", en: "Luxembourger", ar: "لوكسمبورغي" },
  { code: "MG", en: "Malagasy", ar: "مدغشقري" },
  { code: "MY", en: "Malaysian", ar: "ماليزي" },
  { code: "MV", en: "Maldivian", ar: "مالديفي" },
  { code: "ML", en: "Malian", ar: "مالي" },
  { code: "MT", en: "Maltese", ar: "مالطي" },
  { code: "MR", en: "Mauritanian", ar: "موريتاني" },
  { code: "MX", en: "Mexican", ar: "مكسيكي" },
  { code: "MD", en: "Moldovan", ar: "مولدوفي" },
  { code: "MC", en: "Monégasque", ar: "موناكي" },
  { code: "MN", en: "Mongolian", ar: "منغولي" },
  { code: "ME", en: "Montenegrin", ar: "جبل أسود" },
  { code: "MA", en: "Moroccan", ar: "مغربي" },
  { code: "MZ", en: "Mozambican", ar: "موزمبيقي" },
  { code: "MM", en: "Burmese", ar: "بورمي" },
  { code: "NA", en: "Namibian", ar: "ناميبي" },
  { code: "NP", en: "Nepali", ar: "نيبالي" },
  { code: "NL", en: "Dutch", ar: "هولندي" },
  { code: "NZ", en: "New Zealander", ar: "نيوزيلندي" },
  { code: "NI", en: "Nicaraguan", ar: "نيكاراغوي" },
  { code: "NG", en: "Nigerian", ar: "نيجيري" },
  { code: "KP", en: "North Korean", ar: "كوري شمالي" },
  { code: "MK", en: "North Macedonian", ar: "مقدوني شمالي" },
  { code: "NO", en: "Norwegian", ar: "نرويجي" },
  { code: "OM", en: "Omani", ar: "عماني" },
  { code: "PK", en: "Pakistani", ar: "باكستاني" },
  { code: "PS", en: "Palestinian", ar: "فلسطيني" },
  { code: "PA", en: "Panamanian", ar: "بنمي" },
  { code: "PY", en: "Paraguayan", ar: "باراغواي" },
  { code: "PE", en: "Peruvian", ar: "بيروفي" },
  { code: "PH", en: "Filipino", ar: "فلبيني" },
  { code: "PL", en: "Polish", ar: "بولندي" },
  { code: "PT", en: "Portuguese", ar: "برتغالي" },
  { code: "QA", en: "Qatari", ar: "قطري" },
  { code: "RO", en: "Romanian", ar: "روماني" },
  { code: "RU", en: "Russian", ar: "روسي" },
  { code: "RW", en: "Rwandan", ar: "رواندي" },
  { code: "SA", en: "Saudi", ar: "سعودي" },
  { code: "SN", en: "Senegalese", ar: "سنغالي" },
  { code: "RS", en: "Serbian", ar: "صربي" },
  { code: "SG", en: "Singaporean", ar: "سنغافوري" },
  { code: "SK", en: "Slovak", ar: "سلوفاكي" },
  { code: "SI", en: "Slovenian", ar: "سلوفيني" },
  { code: "SO", en: "Somali", ar: "صومالي" },
  { code: "ZA", en: "South African", ar: "جنوب أفريقي" },
  { code: "KR", en: "South Korean", ar: "كوري جنوبي" },
  { code: "SS", en: "South Sudanese", ar: "جنوب سوداني" },
  { code: "ES", en: "Spanish", ar: "إسباني" },
  { code: "LK", en: "Sri Lankan", ar: "سريلانكي" },
  { code: "SD", en: "Sudanese", ar: "سوداني" },
  { code: "SE", en: "Swedish", ar: "سويدي" },
  { code: "CH", en: "Swiss", ar: "سويسري" },
  { code: "SY", en: "Syrian", ar: "سوري" },
  { code: "TW", en: "Taiwanese", ar: "تايواني" },
  { code: "TJ", en: "Tajik", ar: "طاجيكستاني" },
  { code: "TZ", en: "Tanzanian", ar: "تنزاني" },
  { code: "TH", en: "Thai", ar: "تايلاندي" },
  { code: "TN", en: "Tunisian", ar: "تونسي" },
  { code: "TR", en: "Turkish", ar: "تركي" },
  { code: "TM", en: "Turkmen", ar: "تركماني" },
  { code: "UG", en: "Ugandan", ar: "أوغندي" },
  { code: "UA", en: "Ukrainian", ar: "أوكراني" },
  { code: "AE", en: "Emirati", ar: "إماراتي" },
  { code: "GB", en: "British", ar: "بريطاني" },
  { code: "US", en: "American", ar: "أمريكي" },
  { code: "UY", en: "Uruguayan", ar: "أوروغواي" },
  { code: "UZ", en: "Uzbek", ar: "أوزبكستاني" },
  { code: "VE", en: "Venezuelan", ar: "فنزويلي" },
  { code: "VN", en: "Vietnamese", ar: "فيتنامي" },
  { code: "YE", en: "Yemeni", ar: "يمني" },
  { code: "ZM", en: "Zambian", ar: "زامبي" },
  { code: "ZW", en: "Zimbabwean", ar: "زيمبابوي" },
];