import { createClient } from '@supabase/supabase-js';
import { readFileSync } from 'fs';
const sb = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY);
const id = 'a781a5e7-678e-4695-9a13-a7447998aed8';
const path = `Pharaoh/${id}_portrait_${Date.now()}.png`;
const up = await sb.storage.from('personas').upload(path, readFileSync('/tmp/hat_portrait.png'), { contentType: 'image/png', upsert: true });
if (up.error) throw up.error;
const url = sb.storage.from('personas').getPublicUrl(path).data.publicUrl;
const { error } = await sb.from('personas').update({ image_url: url, face_descriptor: null }).eq('id', id);
if (error) throw error;
console.log('OK', url);
