import { createClient } from '@supabase/supabase-js';
import { readFileSync } from 'fs';
const sb = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY);
const id = 'dff15c80-9ec8-4d6e-941a-9d8d76364ee9';
const path = `Pharaoh/${id}_v2_${Date.now()}.png`;
const up = await sb.storage.from('personas').upload(path, readFileSync('/tmp/horemheb_guard.png'), { contentType:'image/png', upsert:true });
if (up.error) throw up.error;
const url = sb.storage.from('personas').getPublicUrl(path).data.publicUrl;
const { error } = await sb.from('personas').update({ image_url: url, face_descriptor: null }).eq('id', id);
if (error) throw error;
console.log('OK', url);
