import { createClient } from '@supabase/supabase-js';
import { readFileSync } from 'fs';
const sb = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY);
const id = '0e0c5a3d-d3c3-45ba-bff2-ba13e26db952';
const path = `Pharaoh/${id}_v2_${Date.now()}.png`;
const up = await sb.storage.from('personas').upload(path, readFileSync('/tmp/khasekhemwy_v2.png'), { contentType:'image/png', upsert:true });
if (up.error) throw up.error;
const url = sb.storage.from('personas').getPublicUrl(path).data.publicUrl;
const { error } = await sb.from('personas').update({ image_url: url, face_descriptor: null }).eq('id', id);
if (error) throw error;
console.log('OK', url);
