import { createClient } from "@supabase/supabase-js";
import fs from "node:fs";
const sb = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY);
const id = "82430cb8-f4eb-4eed-bd26-4a1c11746440";
const bytes = fs.readFileSync("/tmp/amasis_generated.png");
const path = `Pharaoh/${id}_regen_${Date.now()}.png`;
const { error: e1 } = await sb.storage.from("personas").upload(path, bytes, { contentType: "image/png", upsert: true });
if (e1) throw e1;
const { data } = sb.storage.from("personas").getPublicUrl(path);
const { error: e2 } = await sb.from("personas").update({ image_url: data.publicUrl }).eq("id", id);
if (e2) throw e2;
console.log("OK", data.publicUrl);
