import { createClient } from '@supabase/supabase-js';
import fs from 'fs';
const s = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY);
const PID = '538de2cb-fe74-4c0b-8e34-c1264a081201';
const path = `Pharaoh/${PID}_amenemope_${Date.now()}.jpg`;
const bytes = fs.readFileSync('/tmp/amenemope.jpg');
const { error: ue } = await s.storage.from('personas').upload(path, bytes, { contentType: 'image/jpeg', upsert: true });
if (ue) throw ue;
const { data } = s.storage.from('personas').getPublicUrl(path);
const { error: dbe } = await s.from('personas').update({ image_url: data.publicUrl, face_descriptor: null }).eq('id', PID);
if (dbe) throw dbe;
console.log('OK', data.publicUrl);
