import { createClient } from '@supabase/supabase-js';
import fs from 'fs';
const s = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY);
const PID = '8765f7c1-8caf-4ba1-83c9-967026ac88fc';
const path = `Pharaoh/${PID}_amenemhat2_${Date.now()}.jpg`;
const { error: ue } = await s.storage.from('personas').upload(path, fs.readFileSync('/tmp/am2.jpg'), { contentType: 'image/jpeg', upsert: true });
if (ue) throw ue;
const { data } = s.storage.from('personas').getPublicUrl(path);
const { error: dbe } = await s.from('personas').update({ image_url: data.publicUrl, face_descriptor: null }).eq('id', PID);
if (dbe) throw dbe;
console.log('OK', data.publicUrl);
