import { createClient } from '@supabase/supabase-js';
import fs from 'fs';
const s = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY);
const PID = 'bd2c7f89-bbf5-44c0-b097-dadddafbbbde';
const path = `Pharaoh/${PID}_peseshet_${Date.now()}.jpg`;
const { error: ue } = await s.storage.from('personas').upload(path, fs.readFileSync('/tmp/pst.jpg'), { contentType: 'image/jpeg', upsert: true });
if (ue) throw ue;
const { data } = s.storage.from('personas').getPublicUrl(path);
const { error: dbe } = await s.from('personas').update({ image_url: data.publicUrl, face_descriptor: null }).eq('id', PID);
if (dbe) throw dbe;
console.log('OK', data.publicUrl);
