import { createClient } from '@supabase/supabase-js';
import fs from 'fs';
const s = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY);
const PID = '67895b98-185d-46de-afae-22025697bfbd';
const path = `Pharaoh/${PID}_ptahhotep_${Date.now()}.jpg`;
const bytes = fs.readFileSync('/tmp/ptahhotep.jpg');
const { error: ue } = await s.storage.from('personas').upload(path, bytes, { contentType: 'image/jpeg', upsert: true });
if (ue) throw ue;
const { data } = s.storage.from('personas').getPublicUrl(path);
const { error: dbe } = await s.from('personas').update({ image_url: data.publicUrl, face_descriptor: null }).eq('id', PID);
if (dbe) throw dbe;
console.log('OK', data.publicUrl);
