/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminEnrollRouteImport } from './routes/admin.enroll'
import { Route as ApiPublicHooksScanDuplicatesRouteImport } from './routes/api/public/hooks/scan-duplicates'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEnrollRoute = AdminEnrollRouteImport.update({
  id: '/enroll',
  path: '/enroll',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicHooksScanDuplicatesRoute =
  ApiPublicHooksScanDuplicatesRouteImport.update({
    id: '/api/public/hooks/scan-duplicates',
    path: '/api/public/hooks/scan-duplicates',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/admin/enroll': typeof AdminEnrollRoute
  '/api/public/hooks/scan-duplicates': typeof ApiPublicHooksScanDuplicatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/admin/enroll': typeof AdminEnrollRoute
  '/api/public/hooks/scan-duplicates': typeof ApiPublicHooksScanDuplicatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/admin/enroll': typeof AdminEnrollRoute
  '/api/public/hooks/scan-duplicates': typeof ApiPublicHooksScanDuplicatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/admin/enroll'
    | '/api/public/hooks/scan-duplicates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/admin/enroll'
    | '/api/public/hooks/scan-duplicates'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/admin/enroll'
    | '/api/public/hooks/scan-duplicates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksScanDuplicatesRoute: typeof ApiPublicHooksScanDuplicatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/enroll': {
      id: '/admin/enroll'
      path: '/enroll'
      fullPath: '/admin/enroll'
      preLoaderRoute: typeof AdminEnrollRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/hooks/scan-duplicates': {
      id: '/api/public/hooks/scan-duplicates'
      path: '/api/public/hooks/scan-duplicates'
      fullPath: '/api/public/hooks/scan-duplicates'
      preLoaderRoute: typeof ApiPublicHooksScanDuplicatesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminEnrollRoute: typeof AdminEnrollRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEnrollRoute: AdminEnrollRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksScanDuplicatesRoute: ApiPublicHooksScanDuplicatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
