/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FacebookSetupRouteImport } from './routes/facebook-setup'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultIdRouteImport } from './routes/result.$id'
import { Route as AdminSourceReviewRouteImport } from './routes/admin.source-review'
import { Route as AdminEnrollRouteImport } from './routes/admin.enroll'
import { Route as ApiPublicHooksVerifySourceRelevanceRouteImport } from './routes/api/public/hooks/verify-source-relevance'
import { Route as ApiPublicHooksSharePageRouteImport } from './routes/api/public/hooks/share-page'
import { Route as ApiPublicHooksShareFacebookRouteImport } from './routes/api/public/hooks/share-facebook'
import { Route as ApiPublicHooksSaveResultRouteImport } from './routes/api/public/hooks/save-result'
import { Route as ApiPublicHooksRegeneratePersonaImageRouteImport } from './routes/api/public/hooks/regenerate-persona-image'
import { Route as ApiPublicHooksOgImageRouteImport } from './routes/api/public/hooks/og-image'
import { Route as ApiPublicHooksGeneratePersonaImagesRouteImport } from './routes/api/public/hooks/generate-persona-images'
import { Route as ApiPublicHooksGamePersonasRouteImport } from './routes/api/public/hooks/game-personas'
import { Route as ApiPublicHooksGameAnalyzeRouteImport } from './routes/api/public/hooks/game-analyze'
import { Route as ApiPublicHooksCheckSourceUrlsRouteImport } from './routes/api/public/hooks/check-source-urls'
import { Route as ApiPublicFbGameZipRouteImport } from './routes/api/public/fb-game.zip'

const FacebookSetupRoute = FacebookSetupRouteImport.update({
  id: '/facebook-setup',
  path: '/facebook-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultIdRoute = ResultIdRouteImport.update({
  id: '/result/$id',
  path: '/result/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSourceReviewRoute = AdminSourceReviewRouteImport.update({
  id: '/source-review',
  path: '/source-review',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnrollRoute = AdminEnrollRouteImport.update({
  id: '/enroll',
  path: '/enroll',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicHooksVerifySourceRelevanceRoute =
  ApiPublicHooksVerifySourceRelevanceRouteImport.update({
    id: '/api/public/hooks/verify-source-relevance',
    path: '/api/public/hooks/verify-source-relevance',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSharePageRoute = ApiPublicHooksSharePageRouteImport.update({
  id: '/api/public/hooks/share-page',
  path: '/api/public/hooks/share-page',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksShareFacebookRoute =
  ApiPublicHooksShareFacebookRouteImport.update({
    id: '/api/public/hooks/share-facebook',
    path: '/api/public/hooks/share-facebook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSaveResultRoute =
  ApiPublicHooksSaveResultRouteImport.update({
    id: '/api/public/hooks/save-result',
    path: '/api/public/hooks/save-result',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRegeneratePersonaImageRoute =
  ApiPublicHooksRegeneratePersonaImageRouteImport.update({
    id: '/api/public/hooks/regenerate-persona-image',
    path: '/api/public/hooks/regenerate-persona-image',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksOgImageRoute = ApiPublicHooksOgImageRouteImport.update({
  id: '/api/public/hooks/og-image',
  path: '/api/public/hooks/og-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksGeneratePersonaImagesRoute =
  ApiPublicHooksGeneratePersonaImagesRouteImport.update({
    id: '/api/public/hooks/generate-persona-images',
    path: '/api/public/hooks/generate-persona-images',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksGamePersonasRoute =
  ApiPublicHooksGamePersonasRouteImport.update({
    id: '/api/public/hooks/game-personas',
    path: '/api/public/hooks/game-personas',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksGameAnalyzeRoute =
  ApiPublicHooksGameAnalyzeRouteImport.update({
    id: '/api/public/hooks/game-analyze',
    path: '/api/public/hooks/game-analyze',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCheckSourceUrlsRoute =
  ApiPublicHooksCheckSourceUrlsRouteImport.update({
    id: '/api/public/hooks/check-source-urls',
    path: '/api/public/hooks/check-source-urls',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFbGameZipRoute = ApiPublicFbGameZipRouteImport.update({
  id: '/api/public/fb-game/zip',
  path: '/api/public/fb-game/zip',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/facebook-setup': typeof FacebookSetupRoute
  '/admin/enroll': typeof AdminEnrollRoute
  '/admin/source-review': typeof AdminSourceReviewRoute
  '/result/$id': typeof ResultIdRoute
  '/api/public/fb-game/zip': typeof ApiPublicFbGameZipRoute
  '/api/public/hooks/check-source-urls': typeof ApiPublicHooksCheckSourceUrlsRoute
  '/api/public/hooks/game-analyze': typeof ApiPublicHooksGameAnalyzeRoute
  '/api/public/hooks/game-personas': typeof ApiPublicHooksGamePersonasRoute
  '/api/public/hooks/generate-persona-images': typeof ApiPublicHooksGeneratePersonaImagesRoute
  '/api/public/hooks/og-image': typeof ApiPublicHooksOgImageRoute
  '/api/public/hooks/regenerate-persona-image': typeof ApiPublicHooksRegeneratePersonaImageRoute
  '/api/public/hooks/save-result': typeof ApiPublicHooksSaveResultRoute
  '/api/public/hooks/share-facebook': typeof ApiPublicHooksShareFacebookRoute
  '/api/public/hooks/share-page': typeof ApiPublicHooksSharePageRoute
  '/api/public/hooks/verify-source-relevance': typeof ApiPublicHooksVerifySourceRelevanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/facebook-setup': typeof FacebookSetupRoute
  '/admin/enroll': typeof AdminEnrollRoute
  '/admin/source-review': typeof AdminSourceReviewRoute
  '/result/$id': typeof ResultIdRoute
  '/api/public/fb-game/zip': typeof ApiPublicFbGameZipRoute
  '/api/public/hooks/check-source-urls': typeof ApiPublicHooksCheckSourceUrlsRoute
  '/api/public/hooks/game-analyze': typeof ApiPublicHooksGameAnalyzeRoute
  '/api/public/hooks/game-personas': typeof ApiPublicHooksGamePersonasRoute
  '/api/public/hooks/generate-persona-images': typeof ApiPublicHooksGeneratePersonaImagesRoute
  '/api/public/hooks/og-image': typeof ApiPublicHooksOgImageRoute
  '/api/public/hooks/regenerate-persona-image': typeof ApiPublicHooksRegeneratePersonaImageRoute
  '/api/public/hooks/save-result': typeof ApiPublicHooksSaveResultRoute
  '/api/public/hooks/share-facebook': typeof ApiPublicHooksShareFacebookRoute
  '/api/public/hooks/share-page': typeof ApiPublicHooksSharePageRoute
  '/api/public/hooks/verify-source-relevance': typeof ApiPublicHooksVerifySourceRelevanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/facebook-setup': typeof FacebookSetupRoute
  '/admin/enroll': typeof AdminEnrollRoute
  '/admin/source-review': typeof AdminSourceReviewRoute
  '/result/$id': typeof ResultIdRoute
  '/api/public/fb-game/zip': typeof ApiPublicFbGameZipRoute
  '/api/public/hooks/check-source-urls': typeof ApiPublicHooksCheckSourceUrlsRoute
  '/api/public/hooks/game-analyze': typeof ApiPublicHooksGameAnalyzeRoute
  '/api/public/hooks/game-personas': typeof ApiPublicHooksGamePersonasRoute
  '/api/public/hooks/generate-persona-images': typeof ApiPublicHooksGeneratePersonaImagesRoute
  '/api/public/hooks/og-image': typeof ApiPublicHooksOgImageRoute
  '/api/public/hooks/regenerate-persona-image': typeof ApiPublicHooksRegeneratePersonaImageRoute
  '/api/public/hooks/save-result': typeof ApiPublicHooksSaveResultRoute
  '/api/public/hooks/share-facebook': typeof ApiPublicHooksShareFacebookRoute
  '/api/public/hooks/share-page': typeof ApiPublicHooksSharePageRoute
  '/api/public/hooks/verify-source-relevance': typeof ApiPublicHooksVerifySourceRelevanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/facebook-setup'
    | '/admin/enroll'
    | '/admin/source-review'
    | '/result/$id'
    | '/api/public/fb-game/zip'
    | '/api/public/hooks/check-source-urls'
    | '/api/public/hooks/game-analyze'
    | '/api/public/hooks/game-personas'
    | '/api/public/hooks/generate-persona-images'
    | '/api/public/hooks/og-image'
    | '/api/public/hooks/regenerate-persona-image'
    | '/api/public/hooks/save-result'
    | '/api/public/hooks/share-facebook'
    | '/api/public/hooks/share-page'
    | '/api/public/hooks/verify-source-relevance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/facebook-setup'
    | '/admin/enroll'
    | '/admin/source-review'
    | '/result/$id'
    | '/api/public/fb-game/zip'
    | '/api/public/hooks/check-source-urls'
    | '/api/public/hooks/game-analyze'
    | '/api/public/hooks/game-personas'
    | '/api/public/hooks/generate-persona-images'
    | '/api/public/hooks/og-image'
    | '/api/public/hooks/regenerate-persona-image'
    | '/api/public/hooks/save-result'
    | '/api/public/hooks/share-facebook'
    | '/api/public/hooks/share-page'
    | '/api/public/hooks/verify-source-relevance'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/facebook-setup'
    | '/admin/enroll'
    | '/admin/source-review'
    | '/result/$id'
    | '/api/public/fb-game/zip'
    | '/api/public/hooks/check-source-urls'
    | '/api/public/hooks/game-analyze'
    | '/api/public/hooks/game-personas'
    | '/api/public/hooks/generate-persona-images'
    | '/api/public/hooks/og-image'
    | '/api/public/hooks/regenerate-persona-image'
    | '/api/public/hooks/save-result'
    | '/api/public/hooks/share-facebook'
    | '/api/public/hooks/share-page'
    | '/api/public/hooks/verify-source-relevance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  FacebookSetupRoute: typeof FacebookSetupRoute
  ResultIdRoute: typeof ResultIdRoute
  ApiPublicFbGameZipRoute: typeof ApiPublicFbGameZipRoute
  ApiPublicHooksCheckSourceUrlsRoute: typeof ApiPublicHooksCheckSourceUrlsRoute
  ApiPublicHooksGameAnalyzeRoute: typeof ApiPublicHooksGameAnalyzeRoute
  ApiPublicHooksGamePersonasRoute: typeof ApiPublicHooksGamePersonasRoute
  ApiPublicHooksGeneratePersonaImagesRoute: typeof ApiPublicHooksGeneratePersonaImagesRoute
  ApiPublicHooksOgImageRoute: typeof ApiPublicHooksOgImageRoute
  ApiPublicHooksRegeneratePersonaImageRoute: typeof ApiPublicHooksRegeneratePersonaImageRoute
  ApiPublicHooksSaveResultRoute: typeof ApiPublicHooksSaveResultRoute
  ApiPublicHooksShareFacebookRoute: typeof ApiPublicHooksShareFacebookRoute
  ApiPublicHooksSharePageRoute: typeof ApiPublicHooksSharePageRoute
  ApiPublicHooksVerifySourceRelevanceRoute: typeof ApiPublicHooksVerifySourceRelevanceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/facebook-setup': {
      id: '/facebook-setup'
      path: '/facebook-setup'
      fullPath: '/facebook-setup'
      preLoaderRoute: typeof FacebookSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$id': {
      id: '/result/$id'
      path: '/result/$id'
      fullPath: '/result/$id'
      preLoaderRoute: typeof ResultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/source-review': {
      id: '/admin/source-review'
      path: '/source-review'
      fullPath: '/admin/source-review'
      preLoaderRoute: typeof AdminSourceReviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enroll': {
      id: '/admin/enroll'
      path: '/enroll'
      fullPath: '/admin/enroll'
      preLoaderRoute: typeof AdminEnrollRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/hooks/verify-source-relevance': {
      id: '/api/public/hooks/verify-source-relevance'
      path: '/api/public/hooks/verify-source-relevance'
      fullPath: '/api/public/hooks/verify-source-relevance'
      preLoaderRoute: typeof ApiPublicHooksVerifySourceRelevanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/share-page': {
      id: '/api/public/hooks/share-page'
      path: '/api/public/hooks/share-page'
      fullPath: '/api/public/hooks/share-page'
      preLoaderRoute: typeof ApiPublicHooksSharePageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/share-facebook': {
      id: '/api/public/hooks/share-facebook'
      path: '/api/public/hooks/share-facebook'
      fullPath: '/api/public/hooks/share-facebook'
      preLoaderRoute: typeof ApiPublicHooksShareFacebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/save-result': {
      id: '/api/public/hooks/save-result'
      path: '/api/public/hooks/save-result'
      fullPath: '/api/public/hooks/save-result'
      preLoaderRoute: typeof ApiPublicHooksSaveResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/regenerate-persona-image': {
      id: '/api/public/hooks/regenerate-persona-image'
      path: '/api/public/hooks/regenerate-persona-image'
      fullPath: '/api/public/hooks/regenerate-persona-image'
      preLoaderRoute: typeof ApiPublicHooksRegeneratePersonaImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/og-image': {
      id: '/api/public/hooks/og-image'
      path: '/api/public/hooks/og-image'
      fullPath: '/api/public/hooks/og-image'
      preLoaderRoute: typeof ApiPublicHooksOgImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/generate-persona-images': {
      id: '/api/public/hooks/generate-persona-images'
      path: '/api/public/hooks/generate-persona-images'
      fullPath: '/api/public/hooks/generate-persona-images'
      preLoaderRoute: typeof ApiPublicHooksGeneratePersonaImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/game-personas': {
      id: '/api/public/hooks/game-personas'
      path: '/api/public/hooks/game-personas'
      fullPath: '/api/public/hooks/game-personas'
      preLoaderRoute: typeof ApiPublicHooksGamePersonasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/game-analyze': {
      id: '/api/public/hooks/game-analyze'
      path: '/api/public/hooks/game-analyze'
      fullPath: '/api/public/hooks/game-analyze'
      preLoaderRoute: typeof ApiPublicHooksGameAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/check-source-urls': {
      id: '/api/public/hooks/check-source-urls'
      path: '/api/public/hooks/check-source-urls'
      fullPath: '/api/public/hooks/check-source-urls'
      preLoaderRoute: typeof ApiPublicHooksCheckSourceUrlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fb-game/zip': {
      id: '/api/public/fb-game/zip'
      path: '/api/public/fb-game/zip'
      fullPath: '/api/public/fb-game/zip'
      preLoaderRoute: typeof ApiPublicFbGameZipRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminEnrollRoute: typeof AdminEnrollRoute
  AdminSourceReviewRoute: typeof AdminSourceReviewRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEnrollRoute: AdminEnrollRoute,
  AdminSourceReviewRoute: AdminSourceReviewRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  FacebookSetupRoute: FacebookSetupRoute,
  ResultIdRoute: ResultIdRoute,
  ApiPublicFbGameZipRoute: ApiPublicFbGameZipRoute,
  ApiPublicHooksCheckSourceUrlsRoute: ApiPublicHooksCheckSourceUrlsRoute,
  ApiPublicHooksGameAnalyzeRoute: ApiPublicHooksGameAnalyzeRoute,
  ApiPublicHooksGamePersonasRoute: ApiPublicHooksGamePersonasRoute,
  ApiPublicHooksGeneratePersonaImagesRoute:
    ApiPublicHooksGeneratePersonaImagesRoute,
  ApiPublicHooksOgImageRoute: ApiPublicHooksOgImageRoute,
  ApiPublicHooksRegeneratePersonaImageRoute:
    ApiPublicHooksRegeneratePersonaImageRoute,
  ApiPublicHooksSaveResultRoute: ApiPublicHooksSaveResultRoute,
  ApiPublicHooksShareFacebookRoute: ApiPublicHooksShareFacebookRoute,
  ApiPublicHooksSharePageRoute: ApiPublicHooksSharePageRoute,
  ApiPublicHooksVerifySourceRelevanceRoute:
    ApiPublicHooksVerifySourceRelevanceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
