/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultIdRouteImport } from './routes/result.$id'
import { Route as AdminEnrollRouteImport } from './routes/admin.enroll'
import { Route as ApiPublicHooksVerifySourceRelevanceRouteImport } from './routes/api/public/hooks/verify-source-relevance'
import { Route as ApiPublicHooksSharePageRouteImport } from './routes/api/public/hooks/share-page'
import { Route as ApiPublicHooksRegeneratePersonaImageRouteImport } from './routes/api/public/hooks/regenerate-persona-image'
import { Route as ApiPublicHooksOgImageRouteImport } from './routes/api/public/hooks/og-image'
import { Route as ApiPublicHooksGeneratePersonaImagesRouteImport } from './routes/api/public/hooks/generate-persona-images'
import { Route as ApiPublicHooksCheckSourceUrlsRouteImport } from './routes/api/public/hooks/check-source-urls'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultIdRoute = ResultIdRouteImport.update({
  id: '/result/$id',
  path: '/result/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEnrollRoute = AdminEnrollRouteImport.update({
  id: '/enroll',
  path: '/enroll',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicHooksVerifySourceRelevanceRoute =
  ApiPublicHooksVerifySourceRelevanceRouteImport.update({
    id: '/api/public/hooks/verify-source-relevance',
    path: '/api/public/hooks/verify-source-relevance',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSharePageRoute = ApiPublicHooksSharePageRouteImport.update({
  id: '/api/public/hooks/share-page',
  path: '/api/public/hooks/share-page',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRegeneratePersonaImageRoute =
  ApiPublicHooksRegeneratePersonaImageRouteImport.update({
    id: '/api/public/hooks/regenerate-persona-image',
    path: '/api/public/hooks/regenerate-persona-image',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksOgImageRoute = ApiPublicHooksOgImageRouteImport.update({
  id: '/api/public/hooks/og-image',
  path: '/api/public/hooks/og-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksGeneratePersonaImagesRoute =
  ApiPublicHooksGeneratePersonaImagesRouteImport.update({
    id: '/api/public/hooks/generate-persona-images',
    path: '/api/public/hooks/generate-persona-images',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCheckSourceUrlsRoute =
  ApiPublicHooksCheckSourceUrlsRouteImport.update({
    id: '/api/public/hooks/check-source-urls',
    path: '/api/public/hooks/check-source-urls',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/admin/enroll': typeof AdminEnrollRoute
  '/result/$id': typeof ResultIdRoute
  '/api/public/hooks/check-source-urls': typeof ApiPublicHooksCheckSourceUrlsRoute
  '/api/public/hooks/generate-persona-images': typeof ApiPublicHooksGeneratePersonaImagesRoute
  '/api/public/hooks/og-image': typeof ApiPublicHooksOgImageRoute
  '/api/public/hooks/regenerate-persona-image': typeof ApiPublicHooksRegeneratePersonaImageRoute
  '/api/public/hooks/share-page': typeof ApiPublicHooksSharePageRoute
  '/api/public/hooks/verify-source-relevance': typeof ApiPublicHooksVerifySourceRelevanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/admin/enroll': typeof AdminEnrollRoute
  '/result/$id': typeof ResultIdRoute
  '/api/public/hooks/check-source-urls': typeof ApiPublicHooksCheckSourceUrlsRoute
  '/api/public/hooks/generate-persona-images': typeof ApiPublicHooksGeneratePersonaImagesRoute
  '/api/public/hooks/og-image': typeof ApiPublicHooksOgImageRoute
  '/api/public/hooks/regenerate-persona-image': typeof ApiPublicHooksRegeneratePersonaImageRoute
  '/api/public/hooks/share-page': typeof ApiPublicHooksSharePageRoute
  '/api/public/hooks/verify-source-relevance': typeof ApiPublicHooksVerifySourceRelevanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/admin/enroll': typeof AdminEnrollRoute
  '/result/$id': typeof ResultIdRoute
  '/api/public/hooks/check-source-urls': typeof ApiPublicHooksCheckSourceUrlsRoute
  '/api/public/hooks/generate-persona-images': typeof ApiPublicHooksGeneratePersonaImagesRoute
  '/api/public/hooks/og-image': typeof ApiPublicHooksOgImageRoute
  '/api/public/hooks/regenerate-persona-image': typeof ApiPublicHooksRegeneratePersonaImageRoute
  '/api/public/hooks/share-page': typeof ApiPublicHooksSharePageRoute
  '/api/public/hooks/verify-source-relevance': typeof ApiPublicHooksVerifySourceRelevanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/admin/enroll'
    | '/result/$id'
    | '/api/public/hooks/check-source-urls'
    | '/api/public/hooks/generate-persona-images'
    | '/api/public/hooks/og-image'
    | '/api/public/hooks/regenerate-persona-image'
    | '/api/public/hooks/share-page'
    | '/api/public/hooks/verify-source-relevance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/admin/enroll'
    | '/result/$id'
    | '/api/public/hooks/check-source-urls'
    | '/api/public/hooks/generate-persona-images'
    | '/api/public/hooks/og-image'
    | '/api/public/hooks/regenerate-persona-image'
    | '/api/public/hooks/share-page'
    | '/api/public/hooks/verify-source-relevance'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/admin/enroll'
    | '/result/$id'
    | '/api/public/hooks/check-source-urls'
    | '/api/public/hooks/generate-persona-images'
    | '/api/public/hooks/og-image'
    | '/api/public/hooks/regenerate-persona-image'
    | '/api/public/hooks/share-page'
    | '/api/public/hooks/verify-source-relevance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResultIdRoute: typeof ResultIdRoute
  ApiPublicHooksCheckSourceUrlsRoute: typeof ApiPublicHooksCheckSourceUrlsRoute
  ApiPublicHooksGeneratePersonaImagesRoute: typeof ApiPublicHooksGeneratePersonaImagesRoute
  ApiPublicHooksOgImageRoute: typeof ApiPublicHooksOgImageRoute
  ApiPublicHooksRegeneratePersonaImageRoute: typeof ApiPublicHooksRegeneratePersonaImageRoute
  ApiPublicHooksSharePageRoute: typeof ApiPublicHooksSharePageRoute
  ApiPublicHooksVerifySourceRelevanceRoute: typeof ApiPublicHooksVerifySourceRelevanceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$id': {
      id: '/result/$id'
      path: '/result/$id'
      fullPath: '/result/$id'
      preLoaderRoute: typeof ResultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/enroll': {
      id: '/admin/enroll'
      path: '/enroll'
      fullPath: '/admin/enroll'
      preLoaderRoute: typeof AdminEnrollRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/hooks/verify-source-relevance': {
      id: '/api/public/hooks/verify-source-relevance'
      path: '/api/public/hooks/verify-source-relevance'
      fullPath: '/api/public/hooks/verify-source-relevance'
      preLoaderRoute: typeof ApiPublicHooksVerifySourceRelevanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/share-page': {
      id: '/api/public/hooks/share-page'
      path: '/api/public/hooks/share-page'
      fullPath: '/api/public/hooks/share-page'
      preLoaderRoute: typeof ApiPublicHooksSharePageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/regenerate-persona-image': {
      id: '/api/public/hooks/regenerate-persona-image'
      path: '/api/public/hooks/regenerate-persona-image'
      fullPath: '/api/public/hooks/regenerate-persona-image'
      preLoaderRoute: typeof ApiPublicHooksRegeneratePersonaImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/og-image': {
      id: '/api/public/hooks/og-image'
      path: '/api/public/hooks/og-image'
      fullPath: '/api/public/hooks/og-image'
      preLoaderRoute: typeof ApiPublicHooksOgImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/generate-persona-images': {
      id: '/api/public/hooks/generate-persona-images'
      path: '/api/public/hooks/generate-persona-images'
      fullPath: '/api/public/hooks/generate-persona-images'
      preLoaderRoute: typeof ApiPublicHooksGeneratePersonaImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/check-source-urls': {
      id: '/api/public/hooks/check-source-urls'
      path: '/api/public/hooks/check-source-urls'
      fullPath: '/api/public/hooks/check-source-urls'
      preLoaderRoute: typeof ApiPublicHooksCheckSourceUrlsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminEnrollRoute: typeof AdminEnrollRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEnrollRoute: AdminEnrollRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ResultIdRoute: ResultIdRoute,
  ApiPublicHooksCheckSourceUrlsRoute: ApiPublicHooksCheckSourceUrlsRoute,
  ApiPublicHooksGeneratePersonaImagesRoute:
    ApiPublicHooksGeneratePersonaImagesRoute,
  ApiPublicHooksOgImageRoute: ApiPublicHooksOgImageRoute,
  ApiPublicHooksRegeneratePersonaImageRoute:
    ApiPublicHooksRegeneratePersonaImageRoute,
  ApiPublicHooksSharePageRoute: ApiPublicHooksSharePageRoute,
  ApiPublicHooksVerifySourceRelevanceRoute:
    ApiPublicHooksVerifySourceRelevanceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
